<?php 
if(isset($url[2])){
    switch($url[2]){        
        case'delete';
            deletar("produto",$url[3]);
            break;
        case"cadastrar":
            cadastrar('produto');
            break;
        case"alterar":
            alterar('produto');
            break;
        case"editar":    
            include_once('pagina/painel/adm/pagina/produto/view/editarproduto.php');
            break;
    }
}
include_once('pagina/painel/adm/pagina/produto/view/listarproduto.php');