<?php 
if(isset($url[2])){
    switch($url[2]){        
        case'delete';
            deletar("categoria",$url[3]);
            break;
        case"cadastrar":
            cadastrar('categoria');
            break;
        case"alterar":
            alterar('categoria');
            break;
        case"editar":    
            include_once('pagina/painel/adm/pagina/categoria/view/editarCategoria.php');
            break;
    }
}
include_once('pagina/painel/adm/pagina/categoria/view/listar.php');